[workspace]
resolver = "3"
members = ["ast","base","cli", "interpreter", "parser", "tokenizer", "pal", "pal_real", "pal_mock"]

[workspace.dependencies]
relative-path = "2.0.1"
expect-test = "1.5.1"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
tracing-error = "0.2.1"
color-eyre = "0.6.5"

[profile.dev.package."*"]
# Set the default for dependencies in Development mode.
opt-level = 3

[profile.dev]
# Turn on a small amount of optimization in Development mode.
opt-level = 0
lto = false
#debug = false


[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1
