[package]
name = "effy-base"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-error = { workspace = true }
color-eyre = { workspace = true }
relative-path = { workspace = true }
annotate-snippets = "0.12.8"
strip-ansi-escapes = "0.2.1"
yansi = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
